### ISSUE TITLE
12条建议

### ISSUE THREAD

**Issue by dujiajun** [Tantalus13A98B5F/kaleidoscope#2]
前台：
1、颜色。。。我觉得后台挺好看的
2、首页下部的轮播，弄成一张图片感觉修改会不方便吧。
3、更换寝室，选择新寝室，楼栋不显示D/S等字母吗？
4、故障处理、自助排障，超链接的颜色不显眼
后台：
1、值班报名备注禁止输入？
2、请求列表的公告牌输入确定之后显示在ANT列表里面。。。
3、公告牌和添加ANT的输入检查能否显示具体问题，而不是直接“400 Bad Request 请与网管员取得联系”
4、ANT进展确定用顺序而不是倒序吗？
5、ANT已解决之后不自动刷新？还是等待时间太久了？
6、联系大表的TAB的横线不能填充满屏幕？
7、现在公告不能评论吗？
8、个人信息，学院，除了工科平台，还应该有生环平台，理科试验班（虽然这样太细了也不一定必要）？

**Comment by Tantalus13A98B5F** [comment]
前台的颜色问题已经有很多人反映了……不过现在并没有一个快速易实现的方案，所以暂时就这样了，留待来者吧。4可以去处理一下

后台
1. 那是个feature，现在没有开放报名，是这样的
2. bug
3. 这是一个问题，不过局限于后端的设计并不好修改，所以要在前端先做一层验证，看来是这两处的验证翻车了。添加ant有几处，是哪个地方的有问题？
4. 问题不大，改回来吧
5. feature，数据已经更新了（如果没有出bug的话
6. 所有的页面右侧都有留白，是被这个机制限制了
7. 不能评论
8. 现在的架构是易于添加和修改学院的，现在数据库里没有导入全部的学院列表，这个工作让小朋友们在招新之前完成就好

**Comment by taraxacum45e9a** [comment]
前台
2、把文字和图片分开并不好做，涉及到PC和移动端两边的CSS布局
3、首先没必要显示，其实要显示出来只能多加一个框，显得不简洁
4、前端和UI和PM一致认为不需要改
后台
3、前端验证翻车+1

**Comment by Tantalus13A98B5F** [comment]
关于新进展的顺序，还是要用顺序……因为请求有个留言是肯定是要顺序的，一部分用顺序另一部分用逆序感觉并不好
