### ISSUE TITLE
el-menu-item is-active 的小问题

### ISSUE THREAD

**Issue by tkmikan** [Tantalus13A98B5F/kaleidoscope#5]
先从左侧选择一个选一个项目进入，此时其`class="el-menu-item is-active el-menu-item is-active"`，再用右方的按钮切换时，从左侧进入的项目第一个`is-active`仍在
不过就连其他`<li>`的`el-menu-item`都是出现两遍的，咋回事儿啊.jpg

![image](https://user-images.githubusercontent.com/36260601/36006951-f59cd436-0d7a-11e8-9e06-8a6cd6de1d84.png)

![image](https://user-images.githubusercontent.com/36260601/36007166-1d68b6b4-0d7c-11e8-8641-2bd9aabb320c.png)

**Comment by CoffeeddCat** [comment]
这个bug当时没解决到现在还放在这= =

**Comment by Tantalus13A98B5F** [comment]
我记得最搞笑的是去看发现数据都更新了事件也触发了……
