### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by tkmikan** [Tantalus13A98B5F/kaleidoscope#6]
按个人认为的重要程度降序排列（序号变动可能）
1. **后端对不少表单字段添加了长度限制，请前端先验证一下然后红字提醒在输入框下面**，最终期望是提交通过前端检查的表单不会引发400
  需要验证的：
   - 各种最大长度
   - 个人信息的寝室和邮箱的正则（邮箱已经有了）
  前端选手快来~~接锅~~干活呀..
1. 外部更改mac的输入框，建议增加一个类似`onkeyup="value=value.replace(/[^\da-f:-]/ig,'')"`的属性以阻止非法输入（当然用更优雅的方式实现更好）（如果是`oninput`，Chrome似乎没用，但Edge上的体验更好（完全非法字符完全不会显示））右侧预览能做的话最好弄一个同步显示，格式错误时才显示全部X
1. ~~关于icon，为什么是一个`X`~~ 新图标还没放
1. ~~404的页面，全都用那个粉粉的是否可行？~~ -> gitee #IHW5C
1. Login Please的错误提示重定向到登录（有必要的话先退出再登录）（我也不知道我是怎么触发这个提示的，外部主页右上角名字还在orz）（好像是时间太长了）
1. 完成请求之后自动刷新一下 待议
1. 排班相关里面的提交按钮，风格和添加ANT的提交统一一下？暂时不管
1. ~~手机版添加了记住信息开关之后，布局**极丑**~~ 好了
1. ~~添加ANT后，自动转到未完成列表~~（这个好了）（~~最好再自动打开刚才添加的~~ 做不了）
1. ~~ANT/请求的评论记录，斜体名字和竖线靠得太近，建  议  空  格~~ 好了
1. ~~wiki 中的`修改`按钮可能引发歧义，建议改成`历史`~~ 好了
1. ~~请求转报修的时候自动给用户留言相关信息~~ 不改
1. ~~取卡管理选择楼栋，S66出现在了S区第一个~~ 好了
1. ~~在公告页面开关左侧边栏后，要按两次返回才能回到主页~~ 不改
1. ~~手机版后台来个滑动开启/关闭侧边栏怎么样（逃~~ 不做
1. ~~值班报名的后端没有验证 直接post api可以在奇怪的时间段上报名（比如周一2-4），但感觉这个似乎不是大问题（好像也没什么优雅的处理方法x~~ 不改

**Comment by Tantalus13A98B5F** [comment]
wiki你应该是改成功了，部署有特殊操作而已，之后我来吧

**Comment by silencender** [comment]
第二点附：mac输入框可以考虑使用input mask引导用户输入，参考 https://unmanner.github.io/imaskjs/

附：mikan tql

**Comment by taraxacum45e9a** [comment]
@silencender 
[![inputmaxk.png](https://i.loli.net/2018/03/01/5a97d9efbe700.png)](https://i.loli.net/2018/03/01/5a97d9efbe700.png)
